config/routes.rb
Patrickholloway::Application.routes.draw do
  
  devise_for :users
  
  resources :styles
  resources :users
  resources :fonts
  
  get '/user/current_user' => 'backbone_queries#crrnt_user'
  get '/user/current_user_fonts' => 'backbone_queries#crrnt_user_fonts'
  
  get '/welcome' => 'pages#welcome', as: 'welcome'
  get '/about' => 'pages#about', as: 'about'
  get 'talks' => 'pages#talks', as: 'talks'
  get '/home' => 'pages#home', as: 'home'
  get '/resume' => 'pages#resume', as: 'resume'
  
  root :to => 'pages#home'
end

app/models/font.rb
class Font
  include Mongoid::Document
  field :data, type: Hash
  field :name, type: String
  has_and_belongs_to_many :users
end

app/models/style.rb
class Style
  include Mongoid::Document
  has_and_belongs_to_many :user

  field :name, default: 'no name'
  field :h_font_family, default: 'Verdana'
  field :h_font_style, default: 'normal'
  field :h_font_size, default: '16pt'
  field :h_line_height, default: '1.5'
  field :h_text_transform, default: 'normal'
  field :sh_font_family, default: 'Verdana'
  field :sh_font_style, default: 'italic'
  field :sh_font_size, default: '12pt'
  field :sh_line_height, default: '1.1'
  field :sh_text_transform, default: 'normal'
  field :p_font_family, default: 'Verdana'
  field :p_font_style, default: 'normal'
  field :p_font_size, default: '12pt'
  field :p_line_height, default: '1pt'
  field :p_text_transform, default: 'normal'
  
  validates :name,    uniqueness: true,
                      presence: true
end

app/models/user.rb
class User
  include Mongoid::Document
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  validates_presence_of :email
  validates_presence_of :encrypted_password
  
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String
  field :username
  
  validates :username,      :presence => true,
                            :uniqueness => true,
                            :length => {:within => 6..20},
                            :format => { :with => /\A[A-Za-z0-9]+\z/,
                                :message => "can only contain letters and numbers." }

  has_and_belongs_to_many :styles
  has_and_belongs_to_many :fonts
  
  field :font_ids, :type => Array, :default => ["50c62fb3dbc5544faf000032", "50c62fb3dbc5544faf000098", "50c62fb3dbc5544faf0000af", "50c62fb3dbc5544faf0000f6"]
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  def after_sign_in_path_for(user)
    user.sign_in_count += 1
    if user.sign_in_count < 2
      welcome_path
    else  
      styles_path
    end
  end
end

app/controllers/backbone_queries_controller.rb
class BackboneQueriesController < ApplicationController
  
  # Custom backbone queries that don't map to RESTful collection/model mirroring

  respond_to :json
  
  def crrnt_user
    respond_with current_user
  end

  def crrnt_user_fonts
    respond_with current_user.fonts
  end

end

app/controllers/fonts_controller.rb
class FontsController < ApplicationController
  layout "demo"
  
  def index
    @fonts = Font.page(params[:page]).per(50)
    @current_user = current_user
    @user_fonts = @current_user.fonts
   
    respond_to do |format|
          format.html
          format.json  { render :json => Font.all }
    end
  end
  
  def new
    @font = Font.new
  end

  def show
    respond_to do |format|
          format.html
          format.json  { render :json => Font.find(params[:id]) }
    end
  end

  def create
    respond_to do |format|
          format.json  { render :json => Font.create(params[:font]) }
    end
  end
  
  def edit
    Font.find(params[:id])
  end

  def update
    respond_to do |format|
          format.html
          format.json  { render :json => Font.update(params[:id], params[:font]) }
    end
  end

  def destroy
    respond_to do |format|
          format.html
          format.json  { render :json => Font.destroy(params[:id]) }
    end
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout "demo", only: "welcome"
  before_filter :authenticate_user!, only: "welcome"
  
  def home
    @active = 'home' # for bootstrap tab navbar
  end
  
  def about
    @active = 'about' # for bootstrap tab navbar
  end
  
  def resume
    redirect_to '/', notice: "I am not looking for a job!"
    #@active = 'resume' # for bootstrap tab navbar
  end

  def talks
  end

  def welcome
  end
  
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  respond_to :json
  layout "demo"
  before_filter :authenticate_user!

  def index
    @styles = Style.page(params[:page]).per(50)
    respond_to do |format|
          format.html
          format.json  { render :json => Style.all }
    end
  end
  
  def new
    @style = Style.new
    @user = current_user
    @user_fonts = @user.fonts
  end

  def show
    respond_to do |format|
          format.html
          format.json  { render :json => Style.find(params[:id]) }
    end
  end

  def create
    respond_to do |format|
          format.json  { render :json => Style.create(params[:style]) }
    end
  end
  
  def edit
    Style.find(params[:id])
  end

  def update
    respond_to do |format|
          format.html
          format.json  { render :json => Style.update(params[:id], params[:style]) }
    end
  end

  def destroy
    respond_to do |format|
          format.html
          format.json  { render :json => Style.destroy(params[:id]) }
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
  def index
    @users = User.page(params[:page]).per(50)
    respond_to do |format|
          format.html
          format.json  { render :json => User.all }
    end
  end
  
  def new
    @user = User.new
  end

  def show
    respond_to do |format|
          format.html
          format.json  { render :json => User.find(params[:id]) }
    end
  end

  def create
    respond_to do |format|
          format.json  { render :json => User.create(params[:user]) }
    end
  end
  
  def edit
    User.find(params[:id])
  end
  
  def update
    respond_to do |format|
          format.html
          format.json  {
            render :json => User.where(id: params[:id]).update(font_ids: params[:user][:font_ids])
          }
    end
  end

  def destroy
    respond_to do |format|
          format.html
          format.json  { render :json => User.destroy(params[:id]) }
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_error.html.haml
-if alert
	%p.alert.alert
		= alert

app/views/application/_navbar.html.haml
%nav.navbar.navbar-static-top
  .navbar-inner
    .fixed-width
      %a.brand{:href => home_path}PH
      %ul.nav
        -if @active == 'home'
          %li.active
            %a{:href => home_path} Home
        -else
          %li
            %a{:href => home_path} Home
        - if user_signed_in?
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              %span Styles
              %span.caret
            %ul.dropdown-menu
              %li
                = link_to "New Style", new_style_path
              %li
                = link_to "Browse Styles", styles_path
          %li
            = link_to "Browse Fonts", fonts_path
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %span More
            %span.caret
          %ul.dropdown-menu
            %li
              = link_to "GitHub", "https://github.com/patrickjholloway/"
            / %li
            /   = link_to "Demo App", new_user_session_path
            =#%li
            = #link_to "Resume", resume_path
        -if @active == 'about'
          %li.active
            = link_to "About", about_path
        -else
          %li
            = link_to "About", about_path
        -if user_signed_in?
          %li
            =link_to "Log out", destroy_user_session_path, method: :delete

app/views/application/_notice.html.haml
-if notice
	%p.alert.alert
		= notice

app/views/application/_sidenav.html.haml
#side.span4
  = image_tag("patrickholloway.jpg", class: "img-polaroid biopic")
  :plain
    <address class="well span3">
      Patrick Holloway<br>
      <a href="https://github.com/patrickjholloway">Github</a><br>
      <a href="https://twitter.com/digitalpixelpro">@digitalpixelpro</a><br>
      <a href="mailto:#">patrickjholloway@gmail.com</a>
    </address>
  %nav.span3.well{id: "side-nav"}
    %ul.nav.nav-pills.nav-stacked
      %li
        %a{href: home_path}Home
      %li
        %a{href: talks_path}Talks
      %li
        %a{href: about_path}About
      =#%li
      =#%a{href: resume_path}Resume

app/views/fonts/index.html.haml
.row
	%h1 Fonts
	= paginate @fonts
	.span10
		.row
			%section#fonts.span7
				%h2 Add a font
				- @fonts.each do |font|
					- content_for :head do
						= google_webfonts_link_tag font.data["family"] => font.data["variants"]
					%span.font
						= font.data["family"]
						%i.icon-plus.pull-right
					.clearfix
			%section#user_fonts.span3
				%h2 MyFonts
				%ul
					- @user_fonts.each do |font|
						%li.font-simple>= font.name
						.clearfix
				.clearfix
:javascript
	$('document').ready(function(){
		Workshop.fonts.initialize();
	})

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Patrick Holloway - Ember.js Developer
    %meta{:charset => "UTF-8"}
    %meta{:name => "google", :value => "notranslate"}
    %meta{:content => "en", "http-equiv" => "Content-Language"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = yield :head
    %link{:href => "http://fonts.googleapis.com/css?family=Dancing+Script:400,700|Oswald:400,700,300|Open+Sans:400,700,300", :rel => "stylesheet", :type => "text/css"}/
    = csrf_meta_tags
  %body
    = render "navbar", locals: @active
    #main
      #content_wrapper
        = render "notice"
        = render "error"
        = yield
    = render "footer"

app/views/layouts/demo.html.haml
!!!
%html
  %head
    %title Web Font Workshop
    %meta{:charset => "UTF-8"}
    %meta{:name => "google", :value => "notranslate"}
    %meta{:content => "en", "http-equiv" => "Content-Language"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = yield :head
    %link{:href => "http://fonts.googleapis.com/css?family=Dancing+Script:400,700|Oswald:400,700,300|Open+Sans:400,700,300", :rel => "stylesheet", :type => "text/css"}/
    = csrf_meta_tags
  %body
    = render "navbar", locals: @active
    #main
      #content_wrapper
        = render "notice"
        = render "error"
        = yield
    = render "footer"
    :javascript
      $('document').ready(function(){
        Workshop.devise.initialize();
      })

app/views/pages/about.html.haml
#about.row
  #bio.span6
    %h2 Hello!
    %p My name is Patrick Holloway and I am a self-taught web weveloper from Boston. I love nice clean code that is readable, reusable, and elegant. I am incredibly passionate about my work and love learning more.

    %p I went to school for computer science for a few years before I became a Fine Art Photography major. As it turns out, I still have code running through these veins, because I'm back in it and I'm exploring emerging web technologies like Ember.js, WebSockets, and wearable medical devices.

    %p Being self-taught, I am passionate about giving back to the community that provided me the opportunity educate myself. If it weren't for those who took the time to write blogs, make screencasts, and write books, I would still be working three jobs and barely scraping by. My ambitions are to write code that makes a diffence in people's lives and to help mentor others learning the trade.

    %p Currently I am working as an Ember.js/Rails engineer on the Open Research Exchange Team at PatientsLikeMe in Cambridge, Massachusetts. In the real world I am just a big nerd that likes to watch the Celtics with my wife (loudly), climb mountains (stoicly), and cook Mexican food (really well).

  = render partial: "sidenav"

app/views/pages/home.html.haml
.row
  .hero-unit.span6
    %h1 Patrick Holloway
    %h2.lead Ember/Rails Developer @ Kinvey
    %p
      :markdown
        Welcome to my site,
    %p
      This site was started as place to send prospective employers, but now that I am happily employed, it is a repository to collect my ramblings and side projects.
    %p
      Here are a few projects I have going:
      %dl
        %dt
          %a= link_to "Dungeon Post", "https://github.com/patrickjholloway/dungeon-post"
        %dd.spaced-vertical
          An web client I am building for hosting the tabletop RPG, Pathfinder. I built this to teach myself Ember.js.
        %dt
          %a{href: talks_path}Talks
        %dd.spaced-vertical Talks I have given at Boston Developer Meetups on Ember.js

  = render partial: "sidenav"

app/views/pages/home_old.html.haml
.row
	.hero-unit.span6
		%h1 Patrick Holloway
		%h2.lead Junior Rails Developer
		%p.pull-left
			%dl
				%dt Front End & UX Design
				%dd HTML, CSS, Javascript
				%dd jQuery & jQuery UI
				%dd AJAX
				%dd Twitter Bootstrap
				%dd Adobe Creative Suite
			%dl
				%dt Rails Development
				%dd HAML & SASS
				%dd Various SQL flavors
				%dd Experience with NoSQL (Mongo, Couch DB, and Neo4j)
				%dd Cloud deployment (Heroku, AWS)
				%dd Implementing all manner of open source ruby gems
				%dd Incorporating available RESTful web APIs
		%a{href: styles_path, class: "btn btn-primary btn-large demo pull-right"}Demo
	= render partial: "sidenav"

app/views/pages/lightning.html.haml
.row
  #bio.span6
    %h1 Talks
    %ul
      %li.spaced-vertical
        %b
          %a{href:"http://www.meetup.com/html5boston/events/119440202/"}Lightning Talks on JS Libraries, Frameworks, and Tool Kits
        %br 
        %a{href:"https://twitter.com/bocoup"} @Bocoup
        %br
        %small May 29th, 2013
        %br
        %a{href:"https://speakerdeck.com/patrickjholloway/ember-dot-js-a-brief-intro"}
          %button.btn Slides

      %li.spaced-vertical
        %b
          %a{href:"http://www.meetup.com/Boston-Ember-js/events/140201892/"} Ember Templates
        %br 
        %a{href:"https://twitter.com/dockyard"} @Dockyard
        %br
        %small October 10, 2013
        %br
        %p
          HandleBars, Emblem, templated bindings and handlebars helpers.
        %a{href:"https://speakerdeck.com/patrickjholloway/ember-templates"}
          %button.btn Slides

      %li.spaced-vertical
        %b
          %a{href:"http://www.meetup.com/Boston-Ember-js/events/146077642/"} Ember & WebSockets
        %br 
        %a{href:"https://twitter.com/Brightcove"} @Brightcove
        %br
        %small November 14, 2013
        %br
        %a{href:"https://speakerdeck.com/patrickjholloway/ember-dot-js-and-websockets"}
        %p
          HandleBars, Emblem, templated bindings and handlebars helpers.
        %button.btn Slides

  = render partial: "sidenav"

app/views/pages/resume.html.haml
%h1 Resume
:markdown
	## Patrick Holloway  
	Ruby on Rails Developer  
	41 Albion St  
	Medford, MA 02155  
	781-960-3127  
	<http://patrickjholloway.herokuapp.com/></code>  
	<patrickjholloway@gmail.com></code>  


	### Summary  
	  Junior Ruby on Rails developer with up-to-date knowledge of best practices and web technologies. Art and design background help compliment a wealth of technology skills. Versed in emerging web development platforms, tools, and languages. Able to quickly learn new technologies and software as needed.

	### Education  
	University of Massachusetts Lowell  
	Graduated Summer 2010  
	BFA Graphic Design  

	### Technical Experience

	Ruby on Rails, Ruby,HTML5, CSS3, jQuery/jQuery UI, Javascript, Twitter Bootstrap, NoSQL(MongoDB/CouchDB), HAML, SASS, Adobe Creative Suite, TextMate.

	Two years of computer science at UMass Lowell prior to beginning graphic design degree program.

	### Related Work History

	#### MusicTown  
	September 2012-Present  
	*Ruby on Rails Developer*

	-	Developing and deploying a full stack Ruby on Rails social media web application from scratch.
	-	Using DRY principals and TDD to create clean and solid code.
	-	Creating back-end, complete with web admin panel.
	-	Developing user interface using technologies like jQuery, jQuery UI, Bootstrap, AJAX, and Page Objects in Javascript.


	#### Patrick Holloway Web Design and Photography
	2009-Present  
	*Sole Proprietor*

	-	Designing custom web pages and generating high quality web content
	-	Developing web interfaces with jQuery, CSS, and Ruby on Rails
	-	Photographing weddings, headshots, and events




	#### Wild Honey Media : Boston, MA
	November 2011-December 2011  
	*Intern*

	-	Photograph local pubs for smart phone app media content
	-	Prepare images for publication using Photoshop and Photoshop Lightroom

	#### Brush Art Gallery : Lowell, MA
	Spring Semester 2010  
	*Web Content and Photoshop Internship*

	-	Generate web galleries for artists on the gallery's website
	-	Using Adobe Photoshop to color correct, straighten perspective, remove backgrounds and generally improve the appearance and consistency of web images
	-	Create photographs of resident and exhibited artist's artwork
	-	Photograph gallery events

	### Other Employment

	#### Patch.com : Andover, MA
	November 2010-Present  
	*Freelance Photographer / Journalist*

	-	Shoot events, sports, and special interest pieces for local news sites throughout the Merrimack Valley
	-	Edit and upload image galleries to the content management system
	-	Collect and submit relevant information for captions
	-	Write corresponding articles to accompany image galleries


	#### FedEx Ground
	June 2010-May 2012  
	*Overnight Loader*


	References
	*Available upon request*
.well
	= link_to "Download", "https://dl.dropbox.com/u/26196414/pholloway2012.doc",class: "btn btn-medium btn-primary"
		
	pholloway2012.doc

app/views/pages/talks.html.haml
.row
  #bio.span6
    %h1 Talks
    %ul
      %li.spaced-vertical
        %b
          %a{href:"http://www.meetup.com/html5boston/events/119440202/"}Lightning Talks on JS Libraries, Frameworks, and Tool Kits
        %br 
        %a{href:"https://twitter.com/bocoup"} @Bocoup
        %br
        %small May 29th, 2013
        %p.spaced-vertical My very first speaking engagement, and my excuse to teach myself Ember. A brief lightning talk reviewing Ember.js and comparing it to other Javascript Frameworks.
        %a.btn{href:"https://speakerdeck.com/patrickjholloway/ember-dot-js-a-brief-intro"} Slides
        %a.btn{href:"https://github.com/patrickjholloway/ember-photo"} Code
        %a.btn{href:"http://www.youtube.com/watch?v=aAMhTiVy1io&t=35m5s"} Video

      %li.spaced-vertical
        %b
          %a{href:"http://www.meetup.com/Boston-Ember-js/events/140201892/"} Ember Templates
        %br 
        %a{href:"https://twitter.com/dockyard"} @Dockyard
        %br
        %small October 10, 2013
        %p.spaced-vertical
          HandleBars, Emblem, templated bindings and handlebars helpers from the bottom up.
        %a.btn{href:"https://speakerdeck.com/patrickjholloway/ember-templates"} Slides
        %a.btn{href:"http://www.youtube.com/watch?v=eUCRk94UVOY&t=1m33s"} Video

      %li.spaced-vertical
        %b
          %a{href:"http://www.meetup.com/Boston-Ember-js/events/146077642/"} Ember & WebSockets
        %br 
        %a{href:"https://twitter.com/Brightcove"} @Brightcove
        %br
        %small November 14, 2013
        %br
        %p.spaced-vertical
          Discussing Ember.js and WebSockets, including a rudimentary demo of a chat application implemented using only Ember, Rails, and Postgres. Also touched on the impact of particating and contributing to the development community.
        %a.btn{href:"https://speakerdeck.com/patrickjholloway/ember-dot-js-and-websockets"} Slides
        %a.btn{href:"https://github.com/patrickjholloway/websocket_ember_demo"} Code
        %a.btn{href:"http://www.youtube.com/watch?v=D6BhK4LyFAE&t=75m23s"} Video
  = render partial: "sidenav"

app/views/pages/welcome.html.haml
#welcome.span10.row
	.span2
		%h2 Welcome
		%ul.nav.nav-list
			%li.nav-header Workshop
			%li
				%a{href:fonts_path}Browse Fonts
			%li
				%a{href:styles_path}Browse Styles
			%li
				%a{href:new_style_path}New Style
	.span7.offset1
		#welcome_box.color-box
			:markdown
				#### What can I do here?
				You can browse through Google Web Fonts, add them to your user account. You can preview them in the context of an article with a heading, lead, and paragraph.

				While styling the article you can change the font and font-size for each section. Once you are satisfied with the style you may save it and share it with other users.

				#### Why?

				Often times as a web designer, choosing a font is difficult when you can't see it in context. Picking individual fonts from Google Web Fonts and swapping them in and out manually in your stylesheets is a pain.
				
				This tool makes it easy to preview different combinations and share them with others. Enjoy!
		- 8.times do
			%i.icon-arrow-down.pull-left
		#welcome_style.transparent-box.span5
			:markdown
				## Web Font Workshop
				#### This is a lead.
				This here is a paragraph. Aliquam vel lorem ligula, a egestas arcu. Nunc a blandit lorem. Donec pellentesque tortor sit amet nibh hendrerit adipiscing. Aliquam tincidunt ultrices eros at condimentum.
	
				Curabitur mollis nibh turpis. Curabitur non magna in dolor ullamcorper elementum. Sed sit amet magna non odio molestie venenatis ut viverra dolor.

app/views/pages/welcome2.html.haml
.row
	.hero-unit.span6
		%h1 Patrick Holloway
		%h2.lead Junior Rails Developer | PatientsLikeMe.com
		%p
      :markdown
        Hi there,
        Welcome to my site
	= render partial: "sidenav"

app/views/styles/_css_attributes.html.haml
#css_attributes
	#header_attrs.offset0
		%h3
			Header
		%ul
			%li 
				font-family: 
				= @style.h_font_family
			%li
				font-size: 
				= @style.h_font_size
			%li
				font style: 
				= @style.h_font_style
			%li
				line height: 
				= @style.h_line_height
			%li
				text-transform: 
				= @style.h_text_transform
		#header_attrs.offset3
			%h3
				Header
			%ul
				%li 
					font-family: 
					= @style.sh_font_family
				%li
					font-size: 
					= @style.sh_font_size
				%li
					font style: 
					= @style.sh_font_style
				%li
					line height: 
					= @style.sh_line_height
				%li
					text-transform: 
					= @style.sh_text_transform
		#header_attrs.offset6
			%h3
				Header
			%ul
				%li 
					font-family: 
					= @style.p_font_family
				%li
					font-size: 
					= @style.p_font_size
				%li
					font style: 
					= @style.p_font_style
				%li
					line height: 
					= @style.p_line_height
				%li
					text-transform: 
					= @style.p_text_transform

			

app/views/styles/index.html.haml
.row.span12
	#style_list.span7
		%h1 Styles
		%p.lead Browse through all user generated styles.
		- @styles.each do |style|
			.color-box.style
				%hgroup
					%h1 Web Font Workshop
					%h2 Test your font combos.
					%p.preview This paragraph exemplifies the type of paragraph that would be used in an example paragraph. If there were a different type of paragraph it might say something different, but it isn't. Don't expect to get a different paragraph any time soon. This is as good as it is going to get.
				%p
					%b Style Name:
					= style.name
					%br
					%b Author:
					-if style.user_ids[0]
						= User.find_by(id: style.user_ids[0]).email
				.disclosure
					%i.icon-chevron-down
					%b Details
				.drawer
					.well
						%h4 Header
						%p
							%b Font Family:
							%span.h_font
								= style.h_font_family
						%p
							%b Font Size
							%span.h_size
								= style.h_font_size
					.well.sh_style
						%h4 Lead
						%p
							%b Font Family:
							%span.sh_font
								= style.sh_font_family
						%p
							%b Font Size
							%span.sh_size
								= style.sh_font_size
					.well.p_style
						%h4 Paragraph
						%p
							%b Font Family:
							%span.p_font
								= style.p_font_family
						%p
							%b Font Size
							%span.p_size
							= style.p_font_size
					
	#style_nav.span2.offset2
		%ul.nav.nav-list
			%li.nav-header Workshop
			%li
				= link_to "New Style", new_style_path, class: "pill"
				= link_to "Add More Fonts", fonts_path
				=link_to "Log out", destroy_user_session_path, method: :delete
	- @styles.each do |style|
		- if style.h_font_family[0] == "'"
			- style.h_font_family[0]=''
		- if style.sh_font_family[0] == "'"
			- style.sh_font_family[0]=''
		-if style.p_font_family[0] == "'"
			- style.p_font_family[0]=''
		- content_for :head do
			%link{:href => "http://fonts.googleapis.com/css?family=#{style.h_font_family.gsub(' ',"+").chomp("'")}", :rel => "stylesheet", :type => "text/css"}
			%link{:href => "http://fonts.googleapis.com/css?family=#{style.sh_font_family.gsub(' ',"+").chomp("'")}", :rel => "stylesheet", :type => "text/css"}
			%link{:href => "http://fonts.googleapis.com/css?family=#{style.p_font_family.gsub(' ',"+").chomp("'")}", :rel => "stylesheet", :type => "text/css"}
:javascript
	$('document').ready(function(){
		Workshop.style_index.initialize();
	})

app/views/styles/new.html.haml
#dashboard.row
	#controls.row
		.span13
			.alert.fade.in.alert-info
				%button.close{"data-dismiss" => "alert"} ×
				:markdown
					#### New Style  
					Create custom styles by pick a unique font and font size for each element. You can click the Heading, Sub-heading, or Paragraph elements below once to change your target. Then just click a font or font size to test it out, you will see your changes right away.

					Just click save when you are done and you can view them in the [Styles](http://www.digitalpixelpro.com/styles) page.
			.row
				= form_tag "update" do
					= label_tag "Name"
					= text_field_tag :name, nil, id: "name_field"
				%article.span6
					%hgroup
						%h1#header_unit Web Font Workshop
						%h2#subheader_unit Test your font combos.
					%p#paragraph_unit This paragraph exemplifies the type of paragraph that would be used in an example paragraph. If there were a different type of paragraph it might say something different, but it isn't. Don't expect to get a different paragraph any time soon. This is as good as it is going to get.
				%section#font_size.span3
					:markdown
						-  40pt
						-  36pt
						-  32pt
						-  28pt
						-  24pt
						-  20pt
						-  16pt
						-  12pt
						-  10.5pt
				%section#fonts.span3
					= link_to "Add some fonts", fonts_path
					- if @user_fonts.count	
						- @user_fonts.each do |font|
							- content_for :head do
								= google_webfonts_link_tag font.data["family"] => font.data["variants"]
							%span.font
								= font.data["family"]
							%span.font-delete
								%i.icon-minus.pull-right
	#dashboard_nav
		.dashboard_nav_inner
			#save
				.btn.btn-success
					%i.icon-file.icon-white
					Save
			#reset
				= link_to '#', {class: "btn btn-danger"}  do
					%i.icon-fire.icon-white
					Reset
:javascript
	$('document').ready(function(){
		Workshop.new_style.initialize();
	})